export const authconstants = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_FAILURE: "LOGIN_FAILURE",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",

    SIGHNUP_REQUEST: "SIGHNUP_REQUEST",
    SIGHNUP_SUCCESS: "SIGHNUP_SUCCESS",
    SIGHNUP_FAILURE: "SIGHNUP_FAILURE",

}

export const miscConstants = {
    ISMENUBAR_OPEN: "ISMENUBAR_OPEN",
    IS_LOGOUTMODAL_OPEN: "IS_LOGOUTMODAL_OPEN",
    IS_LOGINMODAL_OPEN: "IS_LOGINMODAL_OPEN",
    ISPRICEBARLIST: "ISPRICEBARLIST"
}
export const categoryConstants = {
    GETALLCATEGORYLIST_REQUEST: "GETALLCATEGORYLIST_REQUEST",
    GETALLCATEGORYLIST_SUCCESS: "GETALLCATEGORYLIST_SUCCESS",
    GETALLCATEGORYLIST_FAILURE: "GETALLCATEGORYLIST_FAILURE",

    FLEXIBLECATEGORYLIST_REQUEST: "FLEXIBLECATEGORYLIST_REQUEST",
    FLEXIBLECATEGORYLIST_SUCCESS: "FLEXIBLECATEGORYLIST_SUCCESS",
    FLEXIBLECATEGORYLIST_FAILURE: "FLEXIBLECATEGORYLIST_FAILURE",
}

export const optionConstants = {
    OPTIONSLIST_REQUEST: "OPTIONSLIST_REQUEST",
    OPTIONSLIST_SUCCESS: "OPTIONSLIST_SUCCESS",
    OPTIONSLIST_FAILURE: "OPTIONSLIST_FAILURE",
}

export const productconstants = {
    PRODUCTLIST_REQUEST: "PRODUCTLIST_REQUEST",
    PRODUCTLIST_SUCCESS: "PRODUCTLIST_SUCCESS",
    PRODUCTLIST_FAILURE: "PRODUCTLIST_FAILURE",

    PRODUCTLISTHOME_REQUEST:"PRODUCTLISTHOME_REQUEST",
    PRODUCTLISTHOME_SUCCESS:"PRODUCTLISTHOME_SUCCESS",
    PRODUCTLISTHOME_FAILURE:"PRODUCTLISTHOME_FAILURE",
}

export const wishlistsConstants = {
    GETWISHLISTS_REQUEST: "GETWISHLISTS_REQUEST",
    GETWISHLISTS_SUCCESS: "GETWISHLISTS_SUCCESS",
    GETWISHLISTS_FAILURE: "GETWISHLISTS_FAILURE",

    DELETEWISHLIST_SUCCESS: "DELETEWISHLIST_SUCCESS",

    ADDWISHLIST_REQUEST: "ADDWISHLIST_REQUEST",
    ADDWISHLIST_SUCCESS: "ADDWISHLIST_SUCCESS",
    ADDWISHLIST_FAILURE: "ADDWISHLIST_FAILURE",
}

export const cartConstatnts = {
    GETCARTLIST_REQUEST: "GETCARTLIST_REQUEST",
    GETCARTLIST_SUCCESS: "GETCARTLIST_SUCCESS",
    GETCARTLIST_FAILURE: "GETCARTLIST_FAILURE",

    ADDTOCART_REQUEST: "ADDTOCART_REQUEST",
    ADDTOCART_SUCCESS: "ADDTOCART_SUCCESS",
    ADDTOCART_FAILURE: "ADDTOCART_FAILURE",

    CART_COUNT: "CART_COUNT"
}
export const adressConstants = {
    ADDRESSLIST_REQUEST: "ADDRESSLIST_REQUEST",
    ADDRESSLIST_SUCCESS: "ADDRESSLIST_SUCCESS",
    ADDRESSLIST_FAILURE: "ADDRESSLIST_FAILURE",

    ADDRESSADD_REQUEST: "ADDRESSADD_REQUEST",
    ADDRESSADD_SUCCESS: "ADDRESSADD_SUCCESS",
    ADDRESSADD_FAILURE: "ADDRESSLIST_FAILURE",
}